name: mlorbit_backend
channels:
  - defaults
  - conda-forge  # Added for access to a wider range of packages and more up-to-date versions
dependencies:
  - python=3.10  # Using Python 3.10; consider upgrading to 3.11 or 3.12 for newer features if compatible
  - flask=2.3.2  # Latest stable Flask version as of October 2023
  - flask-cors=3.0.10  # Latest stable version; version 4.0.0 does not exist
  - requests=2.31.0  # Latest stable Requests library
  - pytest=7.4.3  # Latest stable Pytest version for testing
  - flake8=6.1.0  # Latest stable Flake8 version for linting
  - gunicorn=20.2.0  # Latest stable Gunicorn version; ensuring compatibility
  - pandas=2.1.3  # Latest stable Pandas version for data manipulation
  - numpy=1.26.6  # Latest patch release of NumPy for scientific computing
  - pip:
      - pytest-cov  # Optional: For test coverage reporting
