name: mlorbit_backend
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - flask=2.3.2
  - flask-cors=3.0.10
  - requests=2.31.0
  - pytest=7.4.3
  - flake8=6.1.0
  - gunicorn=20.2.0
  - pandas=2.1.3
  - numpy=1.26.6
  - pip:
      - pytest-cov
