name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Backend and Frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]
        node-version: [16.x]

    env:
      PROJECT_NAME: ${{ github.repository }}
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # -------------------
      # Backend Setup
      # -------------------
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('mlorbit_backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Backend Dependencies
        working-directory: mlorbit_backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Backend Tests
        working-directory: mlorbit_backend
        run: |
          pip install pytest
          pytest || echo "No backend tests found, skipping."

      # -------------------
      # Frontend Setup
      # -------------------
      - name: Set Up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache npm Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('mlorbit_frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Frontend Dependencies
        working-directory: mlorbit_frontend
        run: npm install

      - name: Run Frontend Tests
        working-directory: mlorbit_frontend
        run: npm test -- --watchAll=false || echo "No frontend tests found, skipping."

      - name: Build Frontend
        working-directory: mlorbit_frontend
        run: npm run build

      # -------------------
      # Display Environment Info
      # -------------------
      - name: Display Environment Info
        run: |
          echo "🚀 Repository: $PROJECT_NAME"
          echo "🐧 Branch: $BRANCH_NAME"
          echo "🖥️ Runner OS: ${{ runner.os }}"

      # -------------------
      # Upload Artifacts
      # -------------------
      - name: Upload Frontend Build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: mlorbit_frontend/build/

      - name: Upload Backend Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: backend-logs
          path: mlorbit_backend/logs/ || echo "No logs found."
