name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: mlorbit_backend/environment.yml  # Correct path to your environment.yml
          auto-activate-base: false
          activate-environment: mlorbit_backend

      - name: Verify Conda Environment
        run: |
          conda info
          conda list

      - name: Lint with flake8
        run: |
          flake8 mlorbit_backend/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 mlorbit_backend/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest mlorbit_backend/
